repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Or any other recent version; pre-commit auto-updates this easily
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
